[package]
name = "yuaiserver"
version = "0.1.0"
edition = "2021"

[dependencies]
webrtc = "0.6"
hyper = { version = "0.14", features = ["server", "tcp", "http1", "http2"] }
hyper-rustls = { version = "0.24", features = ["http1", "http2"] }
rustls = "0.21"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.20"
tungstenite = "0.20"
quinn = "0.10"
tracing = "0.1"
tracing-subscriber = "0.3"
jsonwebtoken = "8"
serde = { version = "1", features = ["derive"] }
toml = "0.7"
base64 = "0.21"
futures = "0.3"
rustls-pemfile = "1"
rustls-pki-types = "1"
