[package]
name = "yuaiserver"
version = "0.1.0"
edition = "2021"

[dependencies]
hyper = { version = "0.14", features = ["server", "tcp", "http1", "http2", "stream"] }
hyper-rustls = "0.27"
rustls = "0.23"
tokio = { version = "1.0", features = ["full"] }
tokio-rustls = "0.26"
tokio-stream = "0.1"
tokio-tungstenite = "0.20"
tungstenite = "0.20"
tracing = "0.1"
tracing-subscriber = "0.3"
serde = { version = "1.0", features = ["derive"] }
toml = "0.7"
jsonwebtoken = "8.3"
base64 = "0.21"
dashmap = "5.5"
quinn = "0.11.0"
futures = "0.3"
rustls-pemfile = "1.0"
webrtc = "0.12.0"
