worker_threads = 16 # Сколько юнг бегает по палубе
trusted_host = "localhost"

http_port = 8888 		# Порт для старых шлюпок (HTTP)
https_port = 8443 		# Порт для бронированных крейсеров (HTTPS)
quic_port = 8444 		# Порт для гиперскоростных звездолетов (QUIC)

# Где лежит сундук с шифрами
cert_path = "cert.pem"
# Где лежит ключ от сундука	
key_path = "key.pem"
# Где лежат свитки рейда	
log_path = "yuaiserver.log"
# Тайный пиратский код для проверки пропусков	
jwt_secret = "password"

# Лимиты скорости — сколько добычи можно утащить за раз!
guest_rate_limit = 10          # Лимит для гостей, что шатаются без дела
whitelist_rate_limit = 100     # Лимит для друзей капитана, что в белом списке
blacklist_rate_limit = 5       # Лимит для шпионов, чтоб не лезли слишком часто
rate_limit_window = 60         # Сколько секунд ждать, пока трюм снова откроется
# Ограничение на добычу в трюме, чтоб шпионы не затопили корабль!
max_request_body_size = 1048576 # 1 МБ — предел трюма для запросов, больше не лезет!

# Маяки для телепортации
ice_servers = ["stun:stun.l.google.com:19302", "stun:stun.example.com:3478"]

# Космический атлас — куда лететь и что отдавать!
[[locations]]
path = "/"
response = "Добро пожаловать в космопорт, пришелец!"
headers = [
    ["Content-Type", "text/plain; charset=utf-8"],
    ["X-Welcome", "Yo-ho-ho"]
]
[[locations]]
path = "/api"
response = "{\"message\": \"Это API endpoint планеты Солярис!\"}"
headers = [
    ["Content-Type", "application/json"]
]
[[locations]]
path = "/static"
response = "Через гиперпространство в Торговый Пост, йо-хо-хо!"
