# Порт для старых шлюпок (HTTP), как номер причала
http_port = 80
# Порт для бронированных крейсеров (HTTPS)
https_port = 443
# Порт для гиперскоростных звездолетов (QUIC)
quic_port = 444
# Где лежит сундук с шифрами
cert_path = "cert.pem"
# Где лежит ключ от сундука
key_path = "key.pem"
# Тайный пиратский код для проверки пропусков
jwt_secret = "your_jwt_secret"
# Сколько юнг бегает по палубе
worker_threads = 8

# Лимиты скорости — сколько добычи можно утащить за раз!
guest_rate_limit = 10          # Лимит для гостей, что шатаются без дела
whitelist_rate_limit = 100     # Лимит для друзей капитана, что в белом списке
blacklist_rate_limit = 5       # Лимит для шпионов, чтоб не лезли слишком часто
rate_limit_window = 60         # Сколько секунд ждать, пока трюм снова откроется

# Маяки для телепортации
ice_servers = ["stun:stun.l.google.com:19302", "stun:stun.example.com:3478"]

# Космический атлас — куда лететь и что отдавать!
[[locations]]
path = "/"
response = "Добро пожаловать в космопорт, пришелец!"
[[locations]]
path = "/api"
response = "Это API endpoint планеты Солярис!"
[[locations]]
path = "/static"
response = "Сходу в Торговый Пост за барахлом!"
