# Порт для HTTP соединений (обычно 8080)
http_port = 8080
# Порт для HTTPS соединений (обычно 8443)
https_port = 8443
# Порт для QUIC соединений (обычно 443)
quic_port = 443
# Путь к файлу сертификата для защиты соединений
cert_path = "cert.pem"
# Путь к файлу ключа для сертификата
key_path = "key.pem"
# Секретный ключ для проверки JWT токенов
jwt_secret = "your_jwt_secret"
# Логин для базовой авторизации
basic_auth_login = "admin"
# Пароль для базовой авторизации
basic_auth_password = "password"
# Количество потоков для обработки задач (зависит от процессора, обычно равно числу ядер)
worker_threads = 16
